import {
  Bike,
  Coffee,
  CreditCard,
  Gem,
  HandHeart,
  Landmark,
  Map,
  MapPin,
  Mountain,
  Phone,
  Pill,
  PlaneLanding,
  Search,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Toilet,
  TrainFront,
  Utensils,
  Wifi,
} from 'lucide-vue-next'

const search = (parameters: Record<string, string>) => `/search?${new URLSearchParams(parameters).toString()}`

export const discovery = {
  exploreTypes: [
    { key: 'food', label: 'Food', to: search({ type: 'places', place_type: 'restaurant' }), icon: Utensils, iconClass: 'text-orange-700', iconBackgroundClass: 'bg-orange-50' },
    { key: 'cafes', label: 'Cafes', to: search({ type: 'places', place_type: 'cafe' }), icon: Coffee, iconClass: 'text-amber-800', iconBackgroundClass: 'bg-amber-50' },
    { key: 'shopping', label: 'Shopping', to: search({ type: 'places', place_type: 'shopping' }), icon: ShoppingBag, iconClass: 'text-emerald-700', iconBackgroundClass: 'bg-emerald-50' },
    { key: 'nature', label: 'Nature', to: search({ tag: 'nature' }), icon: Mountain, iconClass: 'text-teal-700', iconBackgroundClass: 'bg-teal-50' },
    { key: 'culture', label: 'Culture', to: search({ tag: 'culture' }), icon: Landmark, iconClass: 'text-indigo-700', iconBackgroundClass: 'bg-indigo-50' },
    { key: 'activities', label: 'Activities', to: search({ type: 'routes' }), icon: Sparkles, iconClass: 'text-rose-700', iconBackgroundClass: 'bg-rose-50' },
  ],
  travelBasics: [
    { title: 'Transportation', description: 'Subway, buses, cards', guideType: 'transport', to: search({ type: 'guides', guide_type: 'transport' }), icon: TrainFront, imagePosition: '46% center' },
    { title: 'SIM & Internet', description: 'eSIM, SIM card, Wi-Fi', guideType: 'sim', to: search({ type: 'guides', guide_type: 'sim' }), icon: Wifi, imagePosition: '58% center' },
    { title: 'Money', description: 'Cards, cash, exchange', guideType: 'payment', to: search({ type: 'guides', guide_type: 'payment' }), icon: CreditCard, imagePosition: '66% center' },
    { title: 'Maps & Navigation', description: 'Naver, Kakao, Google Maps', guideType: 'maps', to: search({ type: 'guides', guide_type: 'maps' }), icon: Map, imagePosition: '54% center' },
    { title: 'Airport arrival', description: 'Train, bus, taxi', guideType: 'arrival', to: search({ type: 'guides', guide_type: 'arrival' }), icon: PlaneLanding, imagePosition: '38% center' },
    { title: 'Before you arrive', description: 'Language, etiquette, basics', guideType: 'etiquette', to: search({ type: 'guides', guide_type: 'etiquette' }), icon: HandHeart, imagePosition: '72% center' },
  ],
  worthExploringNow: [
    'seoul-forest',
    'cafe-onion-seongsu',
    'seongsu-handmade-shoe-street',
  ],
  featuredRoutes: [
    'perfect-5-hours-in-seongsu',
    'half-day-in-bukchon',
    'han-river-sunset-ride',
  ],
  themes: [
    {
      key: 'first-time-in-korea',
      title: 'First time in Korea',
      description: 'The essentials for a confident first visit.',
      to: search({ type: 'guides', tag: 'first-trip' }),
      image: '/images/home/hero-seongsu-editorial.png',
      featured: true,
      tone: 'bg-stone-100',
      icon: Coffee,
      sortOrder: 1,
    },
    {
      key: 'local-korea',
      title: 'Local Korea',
      description: 'Neighborhoods, markets, and everyday Korea.',
      to: search({ tag: 'local' }),
      image: '/images/home/worth-exploring/seongsu-popups.webp',
      featured: false,
      tone: 'bg-slate-100',
      icon: MapPin,
      sortOrder: 2,
    },
    {
      key: 'seasonal-korea',
      title: 'Seasonal Korea',
      description: 'Discover Korea at its best each season.',
      to: search({ q: 'seasonal' }),
      image: '/images/home/worth-exploring/namsan-autumn-night.webp',
      featured: false,
      tone: 'bg-amber-50',
      icon: Mountain,
      sortOrder: 3,
    },
    {
      key: 'night-seoul',
      title: 'Night Seoul',
      description: 'Night views, markets, walks, and late-night experiences.',
      to: search({ q: 'night' }),
      image: '/images/home/worth-exploring/seoul-night-market.webp',
      featured: true,
      tone: 'bg-slate-100',
      icon: Map,
      sortOrder: 4,
    },
    {
      key: 'cycling-korea',
      title: 'Cycling Korea',
      description: 'Riverside rides, bike routes, and slow travel.',
      to: search({ type: 'routes' }),
      image: '/images/home/worth-exploring/han-river-sunset-bike.webp',
      featured: false,
      tone: 'bg-emerald-50',
      icon: Bike,
      sortOrder: 5,
    },
    {
      key: 'hidden-gems',
      title: 'Hidden Gems',
      description: 'Less obvious places worth making the trip for.',
      to: search({ q: 'hidden' }),
      image: null,
      featured: false,
      tone: 'bg-blue-50',
      icon: Gem,
      sortOrder: 6,
    },
  ],
  help: [
    { key: 'emergency', label: 'Emergency', to: '/help/emergency', icon: Phone },
    { key: 'medical-care', label: 'Medical care', to: '/help/medical-care', icon: Stethoscope },
    { key: 'pharmacy', label: 'Pharmacy', to: '/help/pharmacies', icon: Pill },
    { key: 'restroom', label: 'Restroom', to: '/help/restrooms', icon: Toilet },
    { key: 'lost-something', label: 'Lost something', to: '/help/lost-something', icon: Search },
  ],
} as const
