import {
  BookOpen,
  CircleHelp,
  Coffee,
  CreditCard,
  HandHeart,
  Languages,
  Landmark,
  Map,
  MapPin,
  Phone,
  Pill,
  PlaneLanding,
  Route,
  Search,
  ShoppingBag,
  Stethoscope,
  Toilet,
  TrainFront,
  Utensils,
  Wifi,
} from 'lucide-vue-next'

const search = (parameters: Record<string, string>) => `/search?${new URLSearchParams(parameters).toString()}`

export const discovery = {
  exploreTypes: [
    { label: 'Places', description: 'Everyday places to explore', to: search({ type: 'places' }), icon: MapPin },
    { label: 'Food', description: 'Restaurants and local meals', to: search({ type: 'places', place_type: 'restaurant' }), icon: Utensils },
    { label: 'Cafes', description: 'Coffee and creative spaces', to: search({ type: 'places', place_type: 'cafe' }), icon: Coffee },
    { label: 'Shopping', description: 'Stores, markets and pop-ups', to: search({ type: 'places', place_type: 'shopping' }), icon: ShoppingBag },
    { label: 'Routes', description: 'Ready-made ways to explore', to: search({ type: 'routes' }), icon: Route },
    { label: 'Guides', description: 'Practical trip know-how', to: search({ type: 'guides' }), icon: BookOpen },
  ],
  travelBasics: [
    { title: 'Transportation', description: 'Subway, buses, cards', guideType: 'transport', to: search({ type: 'guides', guide_type: 'transport' }), icon: TrainFront, imagePosition: '46% center' },
    { title: 'SIM & Internet', description: 'eSIM, SIM card, Wi-Fi', guideType: 'sim', to: search({ type: 'guides', guide_type: 'sim' }), icon: Wifi, imagePosition: '58% center' },
    { title: 'Money', description: 'Cards, cash, exchange', guideType: 'payment', to: search({ type: 'guides', guide_type: 'payment' }), icon: CreditCard, imagePosition: '66% center' },
    { title: 'Maps & Navigation', description: 'Naver, Kakao, Google Maps', guideType: 'maps', to: search({ type: 'guides', guide_type: 'maps' }), icon: Map, imagePosition: '54% center' },
    { title: 'Airport arrival', description: 'Train, bus, taxi', guideType: 'arrival', to: search({ type: 'guides', guide_type: 'arrival' }), icon: PlaneLanding, imagePosition: '38% center' },
    { title: 'Before you arrive', description: 'Language, etiquette, basics', guideType: 'etiquette', to: search({ type: 'guides', guide_type: 'etiquette' }), icon: HandHeart, imagePosition: '72% center' },
  ],
  worthExploringNow: [
    'seoul-forest',
    'cafe-onion-seongsu',
    'seongsu-handmade-shoe-street',
  ],
  featuredRoutes: [
    'perfect-5-hours-in-seongsu',
  ],
  themes: [
    {
      label: 'Cafes',
      tag: 'cafe',
      description: 'Slow mornings, specialty coffee, and neighborhood favorites.',
      to: search({ tag: 'cafe' }),
      image: '/images/home/hero-seongsu-editorial.png',
      featured: true,
      tone: 'bg-stone-100',
      icon: Coffee,
    },
    {
      label: 'Shopping',
      tag: 'shopping',
      description: 'Independent finds, markets, and modern Korean design.',
      to: search({ tag: 'shopping' }),
      image: null,
      featured: false,
      tone: 'bg-rose-50',
      icon: ShoppingBag,
    },
    {
      label: 'Nature',
      tag: 'nature',
      description: 'Parks, coastlines, mountains, and quiet escapes.',
      to: search({ tag: 'nature' }),
      image: null,
      featured: false,
      tone: 'bg-emerald-50',
      icon: Map,
    },
    {
      label: 'Culture',
      tag: 'culture',
      description: 'Historic streets, museums, traditions, and local stories.',
      to: search({ tag: 'culture' }),
      image: null,
      featured: false,
      tone: 'bg-amber-50',
      icon: Landmark,
    },
    {
      label: 'Local',
      tag: 'local',
      description: 'Neighborhoods, markets, and everyday Korea.',
      to: search({ tag: 'local' }),
      image: null,
      featured: true,
      tone: 'bg-slate-100',
      icon: MapPin,
    },
    {
      label: 'First time',
      tag: 'first-trip',
      description: 'The practical essentials for a confident first visit.',
      to: search({ tag: 'first-trip', type: 'guides' }),
      image: null,
      featured: false,
      tone: 'bg-blue-50',
      icon: BookOpen,
    },
  ],
  help: [
    { label: 'Find a restroom', description: 'Find public restrooms near your current location.', to: '/help/restrooms', icon: Toilet },
    { label: 'Find a pharmacy', description: 'Find nearby pharmacies and check their listed hours.', to: '/help/pharmacies', icon: Pill },
    { label: 'Find medical care', description: 'Find nearby clinics and hospitals with listed hours.', to: '/help/medical-care', icon: Stethoscope },
    { label: 'Medical emergency', description: 'Call 119 and find nearby emergency medical care.', to: '/help/emergency', icon: Phone },
    { label: 'Medical & Pharmacy', description: 'Find care, medicine, and pharmacy information.', guideType: 'emergency', to: search({ type: 'guides', guide_type: 'emergency' }), icon: Stethoscope },
    { label: 'Lost something', description: 'Simple next steps for a lost passport, phone, wallet, bag, or item left on public transport.', to: '/help/lost-something', icon: Search },
    { label: 'Language Help', description: 'When you need help communicating in Korean.', guideType: 'language', to: search({ type: 'guides', guide_type: 'language' }), icon: Languages },
    { label: 'Transport Problem', description: 'Missed the last train? Taxi or transit trouble?', guideType: 'transport', to: search({ type: 'guides', guide_type: 'transport' }), icon: TrainFront },
    { label: 'Travel Help', description: 'Official tourism help and common travel problems.', guideType: 'general', to: search({ type: 'guides', guide_type: 'general' }), icon: CircleHelp },
  ],
} as const
