-- Published runtime content for the generic lost-item guide.
insert into public.problem_guides (id, slug, category, guide_type, title, summary, status, published_at, last_reviewed_at)
values ('d0b3f7f1-6c08-4b55-8e10-000000000601', 'lost-something-else', 'lost-something', 'problem', 'Lost something else in Korea?', 'Start with the place where you most likely left it. If it isn''t there, check Korea''s official lost-and-found service.', 'published', now(), now())
on conflict (slug) do update set category=excluded.category, guide_type=excluded.guide_type, title=excluded.title, summary=excluded.summary, status=excluded.status, published_at=excluded.published_at, last_reviewed_at=excluded.last_reviewed_at;

delete from public.problem_guide_actions a using public.problem_guides g where a.guide_id=g.id and g.slug='lost-something-else';
delete from public.problem_guide_phrases p using public.problem_guides g where p.guide_id=g.id and g.slug='lost-something-else';
delete from public.problem_guide_resources r using public.problem_guides g where r.guide_id=g.id and g.slug='lost-something-else';
delete from public.problem_guide_sections s using public.problem_guides g where s.guide_id=g.id and g.slug='lost-something-else';

insert into public.problem_guide_sections (id,guide_id,section_type,title,body_markdown,interaction_data,sort_order)
select seed.id,g.id,seed.section_type,seed.title,seed.body_markdown,seed.interaction_data,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000611'::uuid,'intro','Start with the most likely place',$md$Contact the station, vehicle, venue, accommodation, or airport where you most likely left the item first.$md$,null::jsonb,10),
('d0b3f7f1-6c08-4b55-8e10-000000000612'::uuid,'choice',null,'',$json${"prompt":"Where do you think you lost it?","options":[{"key":"subway","label":"Subway / Train","title":"Subway / Train","body_markdown":"If you just got off, tell station staff as soon as possible. Share the line or train, direction of travel, approximate time, where you were sitting or standing, and what the item looks like.","action_keys":["related_subway_guide"]},{"key":"taxi","label":"Taxi","title":"Taxi","body_markdown":"Check your taxi app or receipt first. In an app, check the recent trip and its support or contact options. On a receipt, look for taxi or company contact information. If neither is available, note the pickup and drop-off locations, approximate time, vehicle or plate details if remembered, and item description. If it does not turn up, check Korea's official lost-and-found service.","action_keys":["search_lost_found_choice"]},{"key":"bus","label":"Bus","title":"Bus","body_markdown":"Note the route number, direction, boarding stop, alighting stop, approximate time, and item description. Contact the operator or terminal if you can identify it. If it cannot be recovered quickly, check Korea's official lost-and-found service.","action_keys":["search_lost_found_choice"]},{"key":"shop","label":"Café / Restaurant / Shop","title":"Café / Restaurant / Shop","body_markdown":"Return to or contact the place first. Tell staff approximately when you were there, where you were seated or standing, and what the item looks like. Ask whether anything was turned in."},{"key":"hotel","label":"Hotel / Accommodation","title":"Hotel / Accommodation","body_markdown":"Contact the front desk first. Ask them to check your room, housekeeping, lobby or common areas, restaurant or café, and luggage storage if relevant."},{"key":"airport","label":"Airport","title":"Airport","body_markdown":"First work out whether it was lost inside the terminal, at security or immigration, or on the aircraft. Contact the airport's lost-and-found service for terminal items, or the airline for an item left on an aircraft."},{"key":"unknown","label":"Somewhere else / Not sure","title":"Not sure where you lost it?","body_markdown":"Think about the last time you used, carried, or saw the item. Retrace your recent route, payment locations, transport, places where you sat down, recent photos, and location or timeline history if available. Contact the most likely place first. If it still does not turn up, check Korea's official lost-and-found service.","action_keys":["search_lost_found_choice"]}]}$json$::jsonb,20),
('d0b3f7f1-6c08-4b55-8e10-000000000613'::uuid,'step','Was it one of these?',$md$If you lost one of these common travel essentials, use the dedicated guide for more focused next steps.$md$,null::jsonb,30),
('d0b3f7f1-6c08-4b55-8e10-000000000614'::uuid,'step','Describe the item clearly',$md$Record what the item is, its color, brand, size, model if relevant, case or cover, serial number if relevant, stickers, scratches, or other distinctive marks, and the approximate time and place it was lost. Include a photo if available. A photo can make it much easier for staff to identify your item. Do not publicly post sensitive serial or account information.$md$,null::jsonb,40),
('d0b3f7f1-6c08-4b55-8e10-000000000615'::uuid,'step','Search Korea''s official lost & found',$md$Search Police Civil Service 24, Korea's official police lost-and-found service. Recently found items may take time to appear, so check again later if needed.$md$,null::jsonb,50),
('d0b3f7f1-6c08-4b55-8e10-000000000616'::uuid,'step','If you think it was stolen',$md$If there are signs the item was stolen rather than simply lost, contact the police. Do not confront someone yourself.$md$,null::jsonb,60),
('d0b3f7f1-6c08-4b55-8e10-000000000617'::uuid,'good_to_know','Good to know',$md$Recently found items may not appear in the official lost-and-found database immediately. If you have already contacted the most likely location, check again later.$md$,null::jsonb,70),
('d0b3f7f1-6c08-4b55-8e10-000000000618'::uuid,'fallback','Still need help?',$md$The 1330 Travel Helpline can help international visitors with general travel information and communication support.$md$,null::jsonb,80)
) seed(id,section_type,title,body_markdown,interaction_data,sort_order) where g.slug='lost-something-else';

insert into public.problem_guide_actions (id,guide_id,section_id,action_key,action_type,label,description,href,variant,sort_order)
select seed.id,g.id,s.id,seed.action_key,seed.action_type,seed.label,seed.description,seed.href,seed.variant,seed.sort_order from public.problem_guides g join public.problem_guide_sections s on s.guide_id=g.id join (values
('d0b3f7f1-6c08-4b55-8e10-000000000621'::uuid,20,'related_subway_guide','internal','Lost it on the subway?','Follow the dedicated subway lost-item guide.','/help/guides/lost-something-on-the-subway','default',10),
('d0b3f7f1-6c08-4b55-8e10-000000000622'::uuid,20,'search_lost_found_choice','external','Search police lost & found','Search Korea''s official lost-and-found service.','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','primary',20),
('d0b3f7f1-6c08-4b55-8e10-000000000623'::uuid,30,'related_passport_guide','internal','Lost passport guide','Use the dedicated passport-loss guide.','/help/guides/lost-passport','default',30),
('d0b3f7f1-6c08-4b55-8e10-000000000624'::uuid,30,'related_phone_guide','internal','Lost phone guide','Use the dedicated phone-loss guide.','/help/guides/lost-phone','default',40),
('d0b3f7f1-6c08-4b55-8e10-000000000625'::uuid,30,'related_wallet_cards_guide','internal','Lost wallet / cards guide','Use the dedicated wallet and cards guide.','/help/guides/lost-wallet-cards','default',50),
('d0b3f7f1-6c08-4b55-8e10-000000000626'::uuid,30,'related_bag_belongings_guide','internal','Lost bag / belongings guide','Use the dedicated bag and belongings guide.','/help/guides/lost-bag-belongings','default',60),
('d0b3f7f1-6c08-4b55-8e10-000000000627'::uuid,50,'search_lost_found','external','Search police lost & found','Search Korea''s official lost-and-found service.','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','primary',70),
('d0b3f7f1-6c08-4b55-8e10-000000000628'::uuid,60,'call_police_112','phone','Call Police 112','Use this if you think the item was stolen.','tel:112','danger',80),
('d0b3f7f1-6c08-4b55-8e10-000000000629'::uuid,80,'call_1330','phone','Call 1330 Travel Helpline','Multilingual travel support for visitors.','tel:1330','default',90)
) seed(id,section_sort_order,action_key,action_type,label,description,href,variant,sort_order) on s.sort_order=seed.section_sort_order where g.slug='lost-something-else';

insert into public.problem_guide_phrases (id,guide_id,context,text_en,text_ko,romanization,sort_order)
select seed.id,g.id,seed.context,seed.text_en,seed.text_ko,seed.romanization,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000631'::uuid,'General','I lost something.','물건을 잃어버렸어요.','Mulgeoneul ireobeoryeosseoyo.',10),
('d0b3f7f1-6c08-4b55-8e10-000000000632'::uuid,'Item','I lost this item.','이 물건을 잃어버렸어요.','I mulgeoneul ireobeoryeosseoyo.',20),
('d0b3f7f1-6c08-4b55-8e10-000000000633'::uuid,'Last location','I think I left it here.','여기에 두고 간 것 같아요.','Yeogie dugo gan geot gatayo.',30),
('d0b3f7f1-6c08-4b55-8e10-000000000634'::uuid,'Lost and found','Has this been turned in as lost property?','혹시 이 물건이 분실물로 들어왔나요?','Hoksi i mulgeoni bunsilmullo deureowannayo?',40),
('d0b3f7f1-6c08-4b55-8e10-000000000635'::uuid,'Description','It''s black and about this size.','검은색이고 이 정도 크기예요.','Geomeunsaegigo i jeongdo keugiyeyo.',50)
) seed(id,context,text_en,text_ko,romanization,sort_order) where g.slug='lost-something-else';

insert into public.problem_guide_resources (id,guide_id,resource_type,platform,title,description,organization,url,language,last_checked_at,is_active,featured,sort_order)
select seed.id,g.id,seed.resource_type,seed.platform,seed.title,seed.description,seed.organization,seed.url,seed.language,now(),true,false,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000641'::uuid,'official','website','Police Civil Service 24 — Lost & Found','Search Korea''s official police lost-and-found service.','Korean National Police Agency','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','ko',10),
('d0b3f7f1-6c08-4b55-8e10-000000000642'::uuid,'official','website','1330 Travel Helpline','Multilingual travel information and interpretation assistance for international travelers.','Korea Tourism Organization','https://english.visitkorea.or.kr/svc/contents/infoBscView.do?vcontsId=140632','en',20)
) seed(id,resource_type,platform,title,description,organization,url,language,sort_order) where g.slug='lost-something-else';
