-- Published runtime content for the lost bag / belongings guide.
insert into public.problem_guides (id, slug, category, guide_type, title, summary, status, published_at, last_reviewed_at)
values ('d0b3f7f1-6c08-4b55-8e10-000000000501', 'lost-bag-belongings', 'lost-something', 'problem', 'Lost a bag or personal belongings in Korea?', 'Start with the place where you most likely left it. If it isn''t there, use Korea''s official lost-and-found service.', 'published', now(), now())
on conflict (slug) do update set category=excluded.category, guide_type=excluded.guide_type, title=excluded.title, summary=excluded.summary, status=excluded.status, published_at=excluded.published_at, last_reviewed_at=excluded.last_reviewed_at;

delete from public.problem_guide_actions a using public.problem_guides g where a.guide_id=g.id and g.slug='lost-bag-belongings';
delete from public.problem_guide_phrases p using public.problem_guides g where p.guide_id=g.id and g.slug='lost-bag-belongings';
delete from public.problem_guide_resources r using public.problem_guides g where r.guide_id=g.id and g.slug='lost-bag-belongings';
delete from public.problem_guide_sections s using public.problem_guides g where s.guide_id=g.id and g.slug='lost-bag-belongings';

insert into public.problem_guide_sections (id,guide_id,section_type,title,body_markdown,interaction_data,sort_order)
select seed.id,g.id,seed.section_type,seed.title,seed.body_markdown,seed.interaction_data,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000511'::uuid,'intro','Start with the most likely place',$md$Contact the station, vehicle, venue, accommodation, or airport where you most likely left the bag first.$md$,null::jsonb,10),
('d0b3f7f1-6c08-4b55-8e10-000000000512'::uuid,'choice',null,'',$json${"prompt":"Where do you think you lost it?","options":[{"key":"subway","label":"Subway / Train","title":"Subway / Train","body_markdown":"Tell station staff as soon as possible. Share the line or train, direction of travel, approximate time, where you were sitting or standing, and the bag's color, size, and type.","action_keys":["related_subway_guide"]},{"key":"taxi","label":"Taxi","title":"Taxi","body_markdown":"Check your taxi app or receipt. Use the app's recent-trip support or taxi/company contact details. Otherwise note pickup and drop-off locations, approximate time, vehicle or plate details, and the bag description. Then search the official lost-and-found service.","action_keys":["search_lost_found_choice"]},{"key":"bus","label":"Bus","title":"Bus","body_markdown":"Note the route number, direction, boarding and alighting stops, approximate time, and bag description. Contact the operator or terminal if you can identify it, then check the official lost-and-found service.","action_keys":["search_lost_found_choice"]},{"key":"shop","label":"Café / Restaurant / Shop","title":"Café / Restaurant / Shop","body_markdown":"Return to or contact the place. Tell staff when you were there, where you were seated or standing, and what the bag looks like. Ask whether anything was turned in."},{"key":"hotel","label":"Hotel / Accommodation","title":"Hotel / Accommodation","body_markdown":"Ask the front desk to check your room, housekeeping, lobby or common areas, restaurant or café, and luggage storage if relevant."},{"key":"airport","label":"Airport","title":"Airport","body_markdown":"Work out whether it was lost in the terminal, at security or immigration, or on the aircraft. Contact airport lost-and-found for terminal items, or the airline for items left on an aircraft."},{"key":"unknown","label":"Somewhere else / Not sure","title":"Not sure where you lost it?","body_markdown":"Think about the last place you opened, carried, or put down the bag. Retrace your route, transport, places where you sat down, recent purchases or receipts, and photos that may show the bag.","action_keys":["search_lost_found_choice"]}]}$json$::jsonb,20),
('d0b3f7f1-6c08-4b55-8e10-000000000513'::uuid,'do_first','Important items inside?',$md$A bag can contain several important items. For a laptop or other electronics, use the device maker's location or security tools if possible and secure important accounts.$md$,null::jsonb,30),
('d0b3f7f1-6c08-4b55-8e10-000000000514'::uuid,'step','Search Korea''s official lost & found',$md$Search Police Civil Service 24. Newly found items may take time to appear, so check again later if needed.$md$,null::jsonb,40),
('d0b3f7f1-6c08-4b55-8e10-000000000515'::uuid,'step','If you think it was stolen',$md$If there are signs the bag was stolen rather than simply lost, contact the police. Do not confront someone yourself.$md$,null::jsonb,50),
('d0b3f7f1-6c08-4b55-8e10-000000000516'::uuid,'what_you_need','What you''ll need',$md$Record the bag color, size, brand, type, stickers or tags, straps or marks, important contents, time and place last seen, luggage-tag details, and a recent photo. A recent photo can be very useful when asking staff about it.$md$,null::jsonb,60),
('d0b3f7f1-6c08-4b55-8e10-000000000517'::uuid,'good_to_know','Good to know',$md$Lost items may take time to reach a lost-and-found office or appear in the official database. If you contacted the likely location already, check again later.$md$,null::jsonb,70),
('d0b3f7f1-6c08-4b55-8e10-000000000518'::uuid,'fallback','Still need help?',$md$The 1330 Travel Helpline can help international visitors with general travel information and communication support.$md$,null::jsonb,80)
) seed(id,section_type,title,body_markdown,interaction_data,sort_order) where g.slug='lost-bag-belongings';

insert into public.problem_guide_actions (id,guide_id,section_id,action_key,action_type,label,description,href,variant,sort_order)
select seed.id,g.id,s.id,seed.action_key,seed.action_type,seed.label,seed.description,seed.href,seed.variant,seed.sort_order from public.problem_guides g join public.problem_guide_sections s on s.guide_id=g.id join (values
('d0b3f7f1-6c08-4b55-8e10-000000000521'::uuid,20,'related_subway_guide','internal','Lost it on the subway?','Follow the dedicated subway lost-item guide.','/help/guides/lost-something-on-the-subway','default',10),
('d0b3f7f1-6c08-4b55-8e10-000000000522'::uuid,20,'search_lost_found_choice','external','Search police lost & found','Search Korea''s official lost-and-found service.','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','primary',20),
('d0b3f7f1-6c08-4b55-8e10-000000000523'::uuid,30,'related_passport_guide','internal','Passport was inside?','Start the passport-loss process too.','/help/guides/lost-passport','default',30),
('d0b3f7f1-6c08-4b55-8e10-000000000524'::uuid,30,'related_phone_guide','internal','Phone was inside?','Use the phone-loss guide to locate or secure it.','/help/guides/lost-phone','default',40),
('d0b3f7f1-6c08-4b55-8e10-000000000525'::uuid,30,'related_wallet_guide','internal','Wallet or cards were inside?','Use the wallet guide for card safety and lost-and-found steps.','/help/guides/lost-wallet-cards','default',50),
('d0b3f7f1-6c08-4b55-8e10-000000000526'::uuid,30,'find_pharmacy','internal','Find a pharmacy','A nearby pharmacy may be able to help with urgent medication needs.','/help/pharmacies','default',60),
('d0b3f7f1-6c08-4b55-8e10-000000000527'::uuid,30,'find_medical_care','internal','Find medical care','Find nearby medical care if essential medication is needed urgently.','/help/medical-care','default',70),
('d0b3f7f1-6c08-4b55-8e10-000000000528'::uuid,40,'search_lost_found','external','Search police lost & found','Search Korea''s official lost-and-found service.','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','primary',80),
('d0b3f7f1-6c08-4b55-8e10-000000000529'::uuid,50,'call_police_112','phone','Call Police 112','Use this if you think the bag was stolen.','tel:112','danger',90),
('d0b3f7f1-6c08-4b55-8e10-000000000530'::uuid,80,'call_1330','phone','Call 1330 Travel Helpline','Multilingual travel support for visitors.','tel:1330','default',100)
) seed(id,section_sort_order,action_key,action_type,label,description,href,variant,sort_order) on s.sort_order=seed.section_sort_order where g.slug='lost-bag-belongings';

insert into public.problem_guide_phrases (id,guide_id,context,text_en,text_ko,romanization,sort_order)
select seed.id,g.id,seed.context,seed.text_en,seed.text_ko,seed.romanization,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000531'::uuid,'General','I lost my bag.','가방을 잃어버렸어요.','Gabangeul ireobeoryeosseoyo.',10),('d0b3f7f1-6c08-4b55-8e10-000000000532'::uuid,'Last location','I think I left my bag here.','가방을 여기 두고 간 것 같아요.','Gabangeul yeogi dugo gan geot gatayo.',20),('d0b3f7f1-6c08-4b55-8e10-000000000533'::uuid,'Description','It''s a black backpack.','검은색 백팩이에요.','Geomeunsaek baekpaegieyo.',30),('d0b3f7f1-6c08-4b55-8e10-000000000534'::uuid,'Lost and found','Has a bag been turned in?','혹시 분실물로 들어온 가방이 있나요?','Hoksi bunsilmullo deureoon gabangi innayo?',40),('d0b3f7f1-6c08-4b55-8e10-000000000535'::uuid,'Police','I think my bag was stolen.','가방을 도난당한 것 같아요.','Gabangeul donandanghan geot gatayo.',50)
) seed(id,context,text_en,text_ko,romanization,sort_order) where g.slug='lost-bag-belongings';

insert into public.problem_guide_resources (id,guide_id,resource_type,platform,title,description,organization,url,language,last_checked_at,is_active,featured,sort_order)
select seed.id,g.id,seed.resource_type,seed.platform,seed.title,seed.description,seed.organization,seed.url,seed.language,now(),true,false,seed.sort_order from public.problem_guides g cross join (values
('d0b3f7f1-6c08-4b55-8e10-000000000541'::uuid,'official','website','Police Civil Service 24 — Lost & Found','Search Korea''s official police lost-and-found service.','Korean National Police Agency','https://minwon24.police.go.kr/cvlcpt/cvlcptGdInfo.do?cvlcptId=MW-201','ko',10),('d0b3f7f1-6c08-4b55-8e10-000000000542'::uuid,'official','website','1330 Travel Helpline','Multilingual travel information and interpretation assistance for international travelers.','Korea Tourism Organization','https://english.visitkorea.or.kr/svc/contents/infoBscView.do?vcontsId=140632','en',20)
) seed(id,resource_type,platform,title,description,organization,url,language,sort_order) where g.slug='lost-bag-belongings';
