<script setup lang="ts">
import type { AdminGuideFormValues } from '~/composables/useAdminGuides'
definePageMeta({ middleware: 'admin-auth' })
const route = useRoute(); const navigationOpen = ref(false); const saving = ref(false); const saveError = ref(''); const saveSuccess = ref(route.query.notice === 'partial-save' ? 'Guide saved successfully, but some additional data could not be saved. You can continue editing this Guide.' : ''); const id = computed(() => String(route.params.id)); const { getSources, getAdminGuideById, updateAdminGuide } = useAdminGuides()
const { data: guide, error: guideError, refresh } = await useAsyncData(() => `admin-guide-${id.value}`, () => getAdminGuideById(id.value)); const { data: sources, error: sourcesError } = await useAsyncData('admin-guide-sources', getSources)
if (!guide.value && !guideError.value) throw createError({ statusCode: 404, statusMessage: 'Guide not found' })
const values = computed<AdminGuideFormValues | null>(() => { if (!guide.value) return null; const translation = guide.value.guide_translations.find(item => item.language_code === 'en'); return { slug: guide.value.slug, guideType: guide.value.guide_type as AdminGuideFormValues['guideType'], sourceId: guide.value.source_id ?? '', status: guide.value.status as AdminGuideFormValues['status'], featured: guide.value.featured, lastVerifiedAt: guide.value.last_verified_at?.slice(0, 10) ?? '', title: translation?.title ?? '', summary: translation?.summary ?? '', bodyMarkdown: translation?.body_markdown ?? '', coverAltText: guide.value.cover?.alt_text ?? '', coverCreditText: guide.value.cover?.credit_text ?? '' } })
const save = async ({ values: form, coverFile, viewAfterSave }: { values: AdminGuideFormValues; coverFile: File | null; viewAfterSave: boolean }) => { if (!guide.value) return; saving.value = true; saveError.value = ''; saveSuccess.value = ''; try { await updateAdminGuide(id.value, form, coverFile, guide.value.cover); if (viewAfterSave && form.status === 'published') { await navigateTo(`/guides/${form.slug}`); return }; await refresh(); saveSuccess.value = viewAfterSave ? `Guide saved as ${form.status}. Publish it to view it on the public site.` : 'Guide saved successfully.' } catch (failure: unknown) { saveError.value = getAdminGuideSaveError(failure, form.slug) } finally { saving.value = false } }
</script>
<template><div class="min-h-screen bg-slate-50 lg:pl-60"><AdminSidebar :open="navigationOpen" @close="navigationOpen = false" /><AdminHeader title="Edit guide" description="Update Guide content, publishing, and cover image." @menu="navigationOpen = true" /><main class="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8"><p v-if="guideError || sourcesError" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">This guide is unavailable right now.</p><template v-else-if="values && sources && guide"><p v-if="saveError" class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ saveError }}</p><AdminGuideForm :key="guide.id + guide.updated_at" :initial-values="values" :sources="sources" :cover="guide.cover" :saving="saving" :success-message="saveSuccess" @save="save" /></template></main></div></template>
